import bcrypt from 'bcryptjs'
const data ={
   users: [
    {
      name: 'Chad',
      email: 'Chadman@bigdickenergy.com',
      password: bcrypt.hashSync('4321', 8),
      isAdmin: true,
    },
    {
        name:'Simp',
        email: 'simpbux@noballs.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: false,
    }
    ],

    products:[
        {
            name:'Kaho Hinata',
            category:'tsundere',
            image:'/images/waifu.jpg',
            price: 9989.99,
            countInStock: 1075,
            brand: 'BlendS',
            rating: 5,
            numReviews: 15,
            description: 'Cute gamer girl',
        },
        {
            name:'Emilia',
            category:'Innocent',
            image:'/images/Emilia_sexy.jpg',
            price: 2199.95,
            countInStock: 0,
            brand: 'Re:Zero',
            rating: 2.6,
            numReviews: 2,
            description: 'Will literally leave you to die.',
        },
        {
            name:'Mimosa',
            category:'Innocent',
            image:'/images/mimosa.jpg',
            price: 28499.99,
            countInStock: 10,
            brand: 'Black Clover',
            rating: 4.5,
            numReviews: 2200.00,
            description: 'Innocent',
        },
        {
            name:'Rem',
            category:'Violent',
            image:'/images/Rem.jpg',
            price: 69.69,
            countInStock: 40,
            brand: 'Re:Zero',
            rating: 3,
            numReviews: 1900,
            description: 'Demon-Girl-Discount. The thinking mans gril',
        },
        {
            name:'Revy',
            category:'Violent',
            image:'/images/Revy.jpg',
            price: 148666.15,
            countInStock: 50,
            brand: 'Black Lagoon',
            rating: 4.5,
            numReviews: 22,
            description: 'Does not disappoint',
        },
        {
            name:'Makoto',
            category:'Wholesome',
            image:'/images/Makoto.jpg',
            price: 3800.00,
            countInStock: 60,
            brand: 'Yakuza',
            rating: 2,
            numReviews: 3,
            description: 'Cant see but will lead you to a wholesome future',
        },
        {
            name:'Misato',
            category:'Violent',
            image:'/images/misato.jpg',
            price: 22849.99,
            countInStock: 70,
            brand: 'Neon Genesis Evangelion',
            rating: 3.5,
            numReviews: 18,
            description: "Don't worry, you can fix her.",
        },
    ],
};
export default data;