const data ={
    product:[
        {
            _id:'1',
            name:'Kaho Hinata',
            category:'tsundere',
            image:'/images/waifu.jpg',
            price: 9989.99,
            brand: 'BlendS',
            rating: 5,
            numReviews: 15,
            description: 'Cute gamer girl',
        },
        {
            _id:'2',
            name:'Emilia',
            category:'Innocent',
            image:'/images/Emilia_sexy.jpg',
            price: 2199.95,
            brand: 'Re:Zero',
            rating: 2.6,
            numReviews: 2,
            description: 'Will literally leave you to die.',
        },
        {
            _id:'3',
            name:'Mimosa',
            category:'Innocent',
            image:'/images/mimosa.jpg',
            price: 28499.99,
            brand: 'Black Clover',
            rating: 4.5,
            numReviews: 2200,
            description: 'Innocent',
        },
        {
            _id:'4',
            name:'Rem',
            category:'Violent',
            image:'/images/Rem.jpg',
            price: 69.69,
            brand: 'Re:Zero',
            rating: 3,
            numReviews: 1900,
            description: 'Demon-Girl-Discount. The thinking mans gril',
        },
        {
            _id:'5',
            name:'Revy',
            category:'Violent',
            image:'/images/Revy.jpg',
            price: 148666.00,
            brand: 'Black Lagoon',
            rating: 4.5,
            numReviews: 22,
            description: 'Does not disappoint',
        },
        {
            _id:'6',
            name:'Makoto',
            category:'Wholesome',
            image:'/images/Makoto.jpg',
            price: 3800.00,
            brand: 'Yakuza',
            rating: 2,
            numReviews: 3,
            description: 'Cant see but will lead you to a wholesome future',
        },
        {
            _id:'7',
            name:'Misato',
            category:'Violent',
            image:'/images/misato.jpg',
            price: 22849.99,
            brand: 'Neon Genesis Evangelion',
            rating: 3.5,
            numReviews: 18,
            description: "Don't worry, you can fix her.",
        },
    ],
};
export default data;